name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get token
        id: seb-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run release-please-action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.seb-token.outputs.token }}

      - name: Publish to crates.io
        if: steps.release.outputs.release_created
        run: |
          cargo publish --token ${{ secrets.CARGO_TOKEN }} --all-features
